//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.DAL.Context.imdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string Number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Department { get; set; }
        public string GPA { get; set; }
        public string Password { get; set; }
    }
}
